STYLE: report when optional components are not built
- easier to spot that it's not an error

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -58,18 +58,6 @@ echo Start ThirdParty Allwmake
 echo ========================================
 echo
 
-echo ========================================
-echo Build malloc
-echo
-(
-    set -x
-    cd malloc || exit 1
-
-    cpMakeFiles fbsdmalloc fbsdmalloc
-
-    ./Allwmake
-)
-
 
 echo ========================================
 echo Build MPI libraries if required
@@ -310,9 +298,34 @@ then
 fi
 
 
+# -----------------------------------------------------------------------------
+
+
+# malloc routines are optional
+echo ========================================
+echo Build malloc
+echo
+if [ -d malloc/fbsdmalloc ]
+then
+(
+    set -x
+    cd malloc || exit 1
+
+    cpMakeFiles fbsdmalloc fbsdmalloc
+
+    ./Allwmake
+)
+else
+    echo "    optional component was not found"
+fi
+
+
+# ParMGridGen is optional
 echo ========================================
 echo Build ParMGridGen
 echo
+if [ -d ParMGridGen-1.0 ]
+then
 (
     set -x
     cd ParMGridGen-1.0 || exit 1
@@ -322,11 +335,16 @@ echo
     wmake libso MGridGen/IMlib
     wmake libso MGridGen/Lib
 )
+else
+    echo "    optional component was not found"
+fi
 
 
+# Tecio is optional
 echo ========================================
 echo Build Tecio
-echo
+if [ -d tecio ]
+then
 (
     set -x
     cd tecio || exit 1
@@ -334,6 +352,9 @@ echo
 
     wmake libso tecsrc
 )
+else
+    echo "    optional component was not found"
+fi
 
 
 #
