added consistency checks in Allwmake* and make* scripts

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -34,6 +34,15 @@
 [ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit 1
 . $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions
 
+if [ "$PWD" != "$WM_THIRD_PARTY_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+
+
 # export WM settings in a form that GNU configure recognizes
 [ -n "$WM_CC" ]         &&  export CC="$WM_CC"
 [ -n "$WM_CXX" ]        &&  export CXX="$WM_CXX"
diff --git a/AllwmakeLibccmio b/AllwmakeLibccmio
--- a/AllwmakeLibccmio
+++ b/AllwmakeLibccmio
@@ -38,6 +38,15 @@ url="https://wci.llnl.gov/codes/visit/3rd_party/$tarFile"
 [ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit 1
 . $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions
 
+if [ "$PWD" != "$WM_THIRD_PARTY_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+
+
 # get tar.gz file if required
 if [ ! -d ${packageDir} ]
 then
diff --git a/DistClean b/DistClean
--- a/DistClean
+++ b/DistClean
@@ -30,8 +30,15 @@
 #     Distribution clean script for ThirdParty
 #
 #------------------------------------------------------------------------------
-# run from third-party directory only
-[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit
+# run from this third-party directory only
+if [ "$PWD" != "$WM_THIRD_PARTY_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+
 set -x
 
 rm -rf gcc-4.3.3/build
diff --git a/makeGcc b/makeGcc
--- a/makeGcc
+++ b/makeGcc
@@ -37,9 +37,15 @@ gmpPACKAGE=gmp-4.2.4
 mpfrPACKAGE=mpfr-2.4.1
 gccPACKAGE=gcc-4.3.3
 
-# run from third-party directory only
-[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit 1
-. $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions
+# run from this third-party directory only
+if [ "$PWD" != "$WM_THIRD_PARTY_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+. tools/makeThirdPartyFunctions
 
 #------------------------------------------------------------------------------
 usage() {
diff --git a/makeQt b/makeQt
--- a/makeQt
+++ b/makeQt
@@ -35,9 +35,15 @@ QT_VERSION=4.3.5
 QT_HOME=$WM_THIRD_PARTY_DIR/qt-x11-opensource-src-$QT_VERSION
 QT_ARCH_PATH=$QT_HOME/platforms/$WM_OPTIONS
 
-# run from third-party directory only
-[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit 1
-. $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions
+# run from this third-party directory only
+if [ "$PWD" != "$WM_THIRD_PARTY_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+. tools/makeThirdPartyFunctions
 
 # get the number of cores to build on
 getNCOMPPROCS
