various fixups
- added downloadFile to makeThirdPartyFunctions
- AllwmakeLibccmio and downloadFile work on files in download/ directory
  (keeps the source tar files out of the way)

- repair/confirm that makeGcc works for (re)building.
  Interrupt if building one of the (gmp|mpfr|gcc) components fails.

NOTE: gmp, mprf are built with ABI=$ABI (probably undefined).
  The gcc build seems to attempt creating a 32/64 cross-compiler and
  fails if it can't find /usr/include/gnu/stubs-32.h

  -> need to install glibc-devel-32bit to get it to compile.

diff --git a/makeGcc b/makeGcc
--- a/makeGcc
+++ b/makeGcc
@@ -30,7 +30,6 @@
 #     Build script for gmp, mpfr and gcc-4.3.? and gcc-4.4.?
 #
 #------------------------------------------------------------------------------
-
 gmpPACKAGE=gmp-4.2.4
 mpfrPACKAGE=mpfr-2.4.1
 gccPACKAGE="$1"
@@ -74,21 +73,25 @@ MPFR_ARCH_PATH=$WM_THIRD_PARTY_DIR/$mpfrPACKAGE/platforms/$WM_ARCH$WM_COMPILER_A
 # Bulid GMP
 #
 if [ -d $GMP_ARCH_PATH ]
-else
+then
     echo "Already built: $gmpPACKAGE"
 else
+    echo "Starting build: $gmpPACKAGE"
 (
     cd $gmpPACKAGE || exit
     make distclean
-    mkdir build
+    rm -rf build
+    mkdir -p build
     cd build
 
     ../configure ABI=$ABI --prefix=$GMP_ARCH_PATH \
     && make -j $WM_NCOMPPROCS \
-    && make install
-
-    echo "Built: $gmpPACKAGE"
-)
+    && make install \
+    && echo "Built: $gmpPACKAGE"
+) || {
+    echo "Error building: $gmpPACKAGE"
+    exit
+}
 fi
 
 export LD_LIBRARY_PATH="$GMP_ARCH_PATH/lib:$LD_LIBRARY_PATH"
@@ -100,33 +103,40 @@ if [ -d $MPFR_ARCH_PATH ]
 then
     echo "Already built: $mpfrPACKAGE"
 else
+    echo "Starting build: $mpfrPACKAGE"
 (
     cd $mpfrPACKAGE || exit
     make distclean
-    mkdir build
+    rm -rf build
+    mkdir -p build
     cd build
 
     ../configure ABI=$ABI --prefix=$MPFR_ARCH_PATH --with-gmp=$GMP_ARCH_PATH \
     && make -j $WM_NCOMPPROCS \
-    && make install
-
-    echo "Built: $mpfrPACKAGE"
-)
+    && make install \
+    && echo "Built: $mpfrPACKAGE"
+) || {
+    echo "Error building: $mpfrPACKAGE"
+    exit
+}
 fi
 
 export LD_LIBRARY_PATH="$MPFR_ARCH_PATH/lib:$LD_LIBRARY_PATH"
 
 #
 # Build GCC
+# might need 32-bit glibc-devel headers to compile
 #
 if [ -d $GCC_ARCH_PATH ]
 then
     echo "Already built: $gccPACKAGE"
 else
+    echo "Starting build: $gccPACKAGE"
 (
     cd $gccPACKAGE || exit
     make distclean
-    mkdir build
+    rm -rf build
+    mkdir -p build
     cd build
 
     ../configure --prefix=$GCC_ARCH_PATH \
@@ -135,10 +145,12 @@ else
         --with-system-zlib \
         --with-gmp=$GMP_ARCH_PATH --with-mpfr=$MPFR_ARCH_PATH \
     && make -j $WM_NCOMPPROCS \
-    && make install
-
-    echo "Built: $gccPACKAGE"
-)
+    && make install \
+    && echo "Built: $gccPACKAGE"
+) || {
+    echo "Error building: $gccPACKAGE"
+    exit
+}
 fi
 
 
diff --git a/makeQt b/makeQt
--- a/makeQt
+++ b/makeQt
@@ -47,6 +47,7 @@ if [ -d "$QT_ARCH_PATH" ]
 then
     echo "Already built: Qt-$QT_VERSION"
 else
+    echo "Starting build: Qt-$QT_VERSION"
 (
     cd $QT_HOME || exit
 
@@ -57,10 +58,12 @@ else
         -nomake demos \
         -nomake examples \
     && time make -j $WM_NCOMPPROCS \
-    && make install
-
-    echo "Built: Qt-$QT_VERSION"
-)
+    && make install \
+    && echo "Built: Qt-$QT_VERSION"
+) || {
+    echo "Error building: Qt-$QT_VERSION"
+    exit
+}
 fi
 
 # ----------------------------------------------------------------- end-of-file
