ENH: allow -qt-VER shortcut in makeParaView
- uses Qt version corresponding to
  \$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/qt-VER/bin/qmake

ENH: -qmake option can be a path (w/o qmake, or bin/qmake)

- update min requirement to Qt 4.5, newer VTK wants at least 4.6 which
  is also needed due to the qstringbuilder

diff --git a/etc/tools/ParaViewFunctions b/etc/tools/ParaViewFunctions
--- a/etc/tools/ParaViewFunctions
+++ b/etc/tools/ParaViewFunctions
@@ -195,10 +195,9 @@ addPythonSupport()
             PYTHON_LIBRARY=$(ldd $pythonBin | \
                 sed -ne '/libpython/s/.* => \(.*\) (.*/\1/p')
 
-           if [ ! -e "$PYTHON_LIBRARY" ]
-           then
+           [ -e "$PYTHON_LIBRARY" ] || {
                echo "*** Error: Unable to determine path to python library."
-           fi
+           }
         fi
 
         [ -e "$PYTHON_LIBRARY" ] || {
@@ -267,38 +266,62 @@ addMesaSupport()
 
 addQtSupport()
 {
+    QtVersion=none
     [ "${withQT:=false}" = true ] || return
 
     addCMakeVariable "PARAVIEW_BUILD_QT_GUI=ON"
 
-    qmakeExe=qmake
-
+    unset qmakeExe
     if [ -n "$QMAKE_PATH" ]
     then
-        if [ -x "$QMAKE_PATH" ]
+        if [ -d "$QMAKE_PATH" ]
+        then
+            if [ -x "$QMAKE_PATH/qmake" ]
+            then
+                qmakeExe=$QMAKE_PATH/qmake
+            elif [ -x "$QMAKE_PATH/bin/qmake" ]
+            then
+                qmakeExe=$QMAKE_PATH/bin/qmake
+            fi
+        elif [ -x "$QMAKE_PATH" ]
         then
             qmakeExe=$QMAKE_PATH
-            addCMakeVariable QT_QMAKE_EXECUTABLE:FILEPATH=$QMAKE_PATH
-        else
+        fi
+
+        [ -n "$qmakeExe" ] || {
             echo
-            echo "specified QMAKE_PATH does not exist on this machine"
+            echo "qmake not found under specified QMAKE_PATH"
             echo "    QMAKE_PATH=$QMAKE_PATH"
             echo "leaving unspecified"
             echo
-        fi
+        }
     fi
+
+    # default to using qmake from the path
+    if [ -n "$qmakeExe" ]
+    then
+        addCMakeVariable QT_QMAKE_EXECUTABLE:FILEPATH=$qmakeExe
+    else
+        qmakeExe=qmake
+    fi
+
 
     # Check qmake can be found
     if type $qmakeExe >/dev/null 2>&1
     then
         # Check the Qt version selected
-        QtVersion=$($qmakeExe -v | grep Using | sed "s/.* version \(.\..\).*/\1/")
-        QtMajor=$(echo $QtVersion | sed "s/\(.\)\../\1/")
-        QtMinor=$(echo $QtVersion | sed "s/.\.\(.\)/\1/")
+        # parse -> "Using Qt version X.Y.Z in ..."
+        QtVersion=$($qmakeExe -query QT_VERSION)
 
-        if [ $QtMajor -lt 4 -o $QtMinor -lt 3 ]
+        # split Major.Minor.Revision - could also use IFS hacking
+        set -- $(echo "$QtVersion" | sed -e 's/\./ /g')
+
+        QtMajor=$1
+        QtMinor=$2
+
+        if [ $QtMajor -lt 4 -o $QtMinor -lt 5 ]
         then
-            echo "*** Error: Qt version provided < 4.3"
+            echo "*** Error: Qt version provided < 4.5"
             echo "***     Please use the -qmake option to specify the location of a version of Qt >= 4.3 "
             echo "***     e.g."
             echo "***         -qmake /usr/local/qt-4.6.2/bin/qmake"
